config/routes.rb
Rails.application.routes.draw do
  # legacy api
  resources :testimonials, as: :legacy_testimonials do
    get :widget, :on => :collection, as: :legacy_widget
  end

  # current api
  scope "v1" do
    resources :testimonials do
      # redirect the widget request amazon s3
      # s3 file is the user's themeConfig
      get :widget, :on => :collection, :to => proc {|env|
        apikey = env["QUERY_STRING"].split("=")[1]

        if Rails.env.development?
          user = User.find_by_apikey(apikey)
          # note in development we serve the staged attributes directly
          # even for "published" mode. so we always see staging in published.
          [200, {}, [user.standard_themes.get_staged.generate_theme_config]]
        else
          url = Publish::Config.new(apikey, 'blah').endpoint
          # log    = Rails.root.join('log', 'widget.log')
          # line   = "#{apikey}, #{env["HTTP_REFERER"]}, #{DateTime.now} \n"
          # File.open(log, 'a') { |f| f.write(line) } if File.exist?(log)

          [
            307,
            { 'Location' => url, 'Content-Type' => 'text/html'} ,
            ["redirecting to: #{ url }"]
          ]
        end
      }
    end

  end

  # account management
  resource :account, :controller => "users", :only => [:new, :create] do
    get :reset_password, on: :collection, via: [:get, :post]
  end

  resource :session, :controller => "user_sessions" do
    get "single_access", :on => :member
    get "perishable", :on => :member
  end

  namespace :admin do
    resource :account

    get '/', action: "index"
    get :logout
    get :collect
    get :install
    get :manage
    get :editor
    get :widget
    get :thanks
  end

  resources :users do
    member do
      resources :charges
      put :settings, controller: "api/settings", action: "update"

      scope "/testimonials", controller: "api/testimonials", as: :testimonials do
        get "()", :action => :index
        put "()", :action => :update
        post "/save_positions", :action => :save_positions
      end

      scope "/theme_attributes", :controller => "api/theme_attributes", :as => :theme_attributes, constraints: { attribute: /[\w\-\.]+/ } do
        get "/:attribute/staged" , :action => :staged
        put "/:attribute/staged", :action => :update
        get "/:attribute/original", :action => :original
      end

      scope "/theme", controller: "api/theme", as: :theme do
        post "()", action: :create
        post "/publish", action: :publish
        get "/gallery/:theme", action: :show
        get "/:theme_id/stage", action: :set_staged
      end

      scope "/widget", :controller => 'api/widget', :as => :widget do
        get :staged
        get :published
        get "stock/:theme_name", action: "stock"
      end
    end
  end

  # dashboard
  scope "/pinky", :controller => "pinky", :as => "pinky" do
    get "()" ,:action => "index"
    get "users"
    post "as_user"
  end

  root to: redirect('/admin')
end

app/views/admin/_widget-previewer.html.haml
#widget-previewer
  .base-padding
    .btn-group
      %a.btn.btn-primary.js-staging.active{ href: "#", title: "Use the \"staged\" version to preview updates without affecting your live widget." } Staging
      %a.btn.btn-primary.js-production{ href: "#", title: "This widget displays the \"published\" version which appears on your live website." } Production
    #widget-published-wrapper

app/views/admin/_widget_previewer.html.haml
#widget-previewer
  .base-padding
    .btn-group
      %a.btn.btn-primary.js-staging.active{ href: "#", title: "Use the \"staged\" version to preview updates without affecting your live widget." } Staging
      %a.btn.btn-primary.js-production{ href: "#", title: "This widget displays the \"published\" version which appears on your live website." } Production
    #widget-published-wrapper

app/views/admin/collect.html.haml
#layout-editor
  .base-padding
    .data-description
      Send your customers to your testimonial collection form to fill out a testimonial. Testimonials auto-magically appear in your admin panel.

    = form_for @user.tconfig, :url => '/admin/settings', html: { id: "collect-form" } do |f|
      .btn-toolbar
        .btn-group{style: "float:right"}
          %button.btn.btn-success{ type: "submit" } Save & Update
        %h3 Customizations

      #public-link.form-group
        %label External Link
        %input#collector-form-url.form-control{type: "text", value: Rails.application.routes.url_helpers.new_testimonial_url(apikey: @user.apikey) }
      .form-group
        %label Require Email (Yes)
        %input{name: "tconfig[form][email]", type: "checkbox", checked: !!@user.tconfig.form['email'] }
        .indent
          Customers are required to enter a valid email address.
          Use this option if you wish to openly collect testimonials from anyone interested in writing one.
          This way you can maintain contact with people you may not know.

      - %w(rating company location c_position website avatar).each do |field|
        .form-group
          %label{ style:"display:inline-block; width:30%" } #{ field.capitalize } field
          %div{ style:"display:inline-block;" }
            %select{ name: "tconfig[form][#{ field }]" }
              %option{ value: "on" } ON
              %option{ value: "off", selected: [false, "off"].include?(@user.tconfig.form[field]) } OFF


      .form-group
        %label Access Key (optional)
        %input.form-control{name: "tconfig[form][require_key]", type: "text", value: @user.tconfig.form['require_key'] }
        .indent
          New testimonials cannot be created without
          %em this
          valid access key.

      .form-group
        %label Custom Header Message.
        = f.text_area :message, :style => 'width:100%;height:100px', class: "form-control"
        %p.indent
          This text will display at the top of your public form.
          Place your company name here, offer incentives for submitting testimonials,
          or just give a nice thank you.

      .form-group{ style: "display:none" }
        %label Define Meta Data Name
        %input.form-control{name: "tconfig[form][meta]", type: "hidden", value: @user.tconfig.form['meta'] }
        .indent
          Customers are required to enter specific meta data defined below.
          %br/
          %b Example:
          If you wish to collect testimonials from only customers that have
          made purchases, you can place the link onto your order confirmation page. Rather than using
          an email identifier of which you already have, you can pass the order confirmation code or customer_id as meta data.

#layout-previewer
  .base-padding
    #collector-form-view  

app/views/admin/editor.html.haml
%link{ rel: "stylesheet", href: "/codemirror-3.1/lib/codemirror.css" }
%style
  :plain
    .CodeMirror { height:600px }
%link{ rel: "stylesheet", href: "/codemirror-3.1/theme/ambiance.css" }
%script{ src: "/codemirror-3.1/lib/codemirror.js" }
%script{ src: "/codemirror-3.1/mode/xml/xml.js" }
%script{ src: "/codemirror-3.1/mode/css/css.js" }

#layout-editor
  .base-padding
    %button.btn.btn-success.pull-right.js-save Save
    .btn-group.attribute-list

    #derp{style: "margin: 10px 0; position:relative;" }
      #token-list{ style: "position:absolute; right:0" }
      %a.load-original.btn.btn-sm.btn-default{ href: "#" } Reset to Original
    %textarea#code-editor{ style: "width:100%; height:400px;" }

#layout-previewer
  = render partial: "widget_previewer"

app/views/admin/form.erb
<%
  collection_form_url = "#{root_url.chomp('/')}#{new_testimonial_path}?apikey=#{@user.apikey}"
%>
<ul class="grandchild_nav">  
  <li class="collect"><a href="/admin/testimonials/form" class="active" rel="tab-collect">Main Panel</a></li> 
  <li class="help"><a href="#help" rel="tab-help">(help)</a></li> 
</ul> 

<div class="primary-content">

  <div id="tab-collect" class="tab-content">
    <div class="public-link">
      <span>Your Public Form Link:</span> <%= link_to collection_form_url, collection_form_url %>
      <input type="text" style="width:450px;padding:5px;" value="<%= collection_form_url %>" />
    </div>

    <% form_for @user.tconfig, :url => '/admin/settings' do |f| %>
      <div class="round-box-top">Configure Form Settings.</div>
      <div class="round-box-body">
        <fieldset>
          <label>Custom Header Message.</label>
          <%= f.text_area :message, :style => 'width:100%;height:100px' %>
        </fieldset>
        
        <br/>A customer's full name is always required. You can optionally require 3 more fields:

        <fieldset>
          <label>Access Key</label>
          <input type="text" name="tconfig[form][require_key]" value="<%= @user.tconfig.form['require_key'] %>" />
        </fieldset>
        
        <fieldset>
          <label>Require Email (Yes)</label> 
          <input type="checkbox" name="tconfig[form][email]" <%= 'CHECKED' if @user.tconfig.form['email'] %>/>
        </fieldset>
        
        <fieldset>
          <label>Define Meta Data Name</label>
          <input type="text" name="tconfig[form][meta]" value="<%= @user.tconfig.form['meta'] %>" />
        </fieldset>

        <div class="round-box-tabs buttons">
          <button type="submit" class="positive">Save Settings</button>
        </div>
      </div>
    <% end %>

    <div class="indent">
      <h4>Customize Header Message.</h4>
      <div class="indent">
        This text will display at the top of your public form.
        Place your company name here, offer incentives for submitting testimonials,
        or just give a nice thank you.
      </div>
      
      <h4>Require Access Key.</h4>
      <div class="indent">
        New testimonials cannot be created without a valid access key.
      </div>
      
      <h4>Require Email Address.</h4>
      <div class="indent">
        Customers are required to enter a valid email address.
        Use this option if you wish to openly collect testimonials from anyone interested in writing one.
        This way you can maintain contact with people you may not know.
      </div>
      
      <h4>Require Additional Meta Data.</h4>
      <div class="indent">
        Customers are required to enter specific meta data defined below.
        <br/><b>Example:</b> If you wish to collect testimonials from only customers that have 
        made purchases, you can place the link onto your order confirmation page. Rather than using
        an email identifier of which you already have, you can pass the order confirmation code or customer_id as meta data.
      </div>

      <h4>Pre-populating The Public Form.</h4>
      <div class="indent">
        You can easily pre-populate known fields by passing them in the url string.
        <br/><input style="margin:7px 0; padding:5px; width:100%" type="text" value="<%= collection_form_url %>?name=your_customers_name&key=you_private_key&email=customer_email&meta=custom_meta_data" />
        <br/><b>See it in action:</b> <a href="<%= collection_form_url %>?name=your_customers_name&key=you_private_key&email=customer_email&meta=custom_meta_data">View your pre-populated public form</a>
      </div>
    </div>
  
  </div>
  
  
  <div id="tab-help" class="tab-content">
    <h3>Collecting Testimonials Publically.</h3>
    
    <h4>Using Your Public "Add Testimonial" Form.</h4>
    <div class="indent">
      Your public "add testimonial" form can be seen here: <%= link_to collection_form_url, collection_form_url %>
      <br/>You can share this link with all of your customers. Once a customer gives the required identifer information,
      his editable testimonial will be generated for him to fill out.
   </div>
    
    <h4>Tip: Pre-populating The Public Form.</h4>
    <div class="indent">
      Make it easier for customers to submit testimonials by pre-populating
      your public form with necessary identifer information.
      <b>Example:</b>
      <br/>You can restrict testimonial submission to only customers who have made a confirmed purchase
      from you by revealing your pluspanda link on the "order confirmation" page or "thank you" email.
      You can then pass identifier data into the url to pre-populate the fields.
      The pluspanda link would look something like this: 
      <br/><%= link_to "#{collection_form_url}?name=John%20Smith&meta=8239&key=Kas987sf", "#{collection_form_url}?name=John%20Smith&meta=8239&key=Kas987sf" %>
    </div>
  
  </div>

</div>

app/views/admin/index.html.erb
<style>
h2, h3 {
  color:#444;
  margin-bottom:15px;
  }
  p {
    line-height:1.5em;
  }
.tab-content {
  width:750px;
}
.install-page {margin-top:20px;}
.install-page textarea {
  width:100%;
  display:block;
  padding:10px;
  font-size:16px;
  font-weight:bold;
  font-family:courier;
  color:#444;
  background-color:#FFFFCC;

}
</style>

<div style="padding: 25px;">
  <div style="margin-bottom:20px; min-width:600px">
  <% if current_user.premium %>
    <div class="alert alert-success">
      <strong>Thank you for upgrading to unlimited published testimonials!</strong>
      <br>I appreciate your support and look forward to improving pluspanda over time.
    </div>
  <% else %>
    <h3>Publish Unlimited Testimonials for $36 per year.</h3>
    <div class="alert alert-danger" style="margin-top:20px">
      <p><strong>Your account is currently limited to 10 published testimonials.</strong></p>
      <p>New testimonials are always saved so your data is never lost.</p>
      <p>But you can only ever display 10 testimonials on your website.</p>
      <p>
        Pay securely with paypal or with credit card:
      </p>
      <table style="width: 50%; margin-top:20px;">
        <tr>
          <td>
            <strong>Paypal</strong>
            <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="EN3E2SASX9G6C">
            <input type="hidden" name="on0" value="pluspanda-email">
            <input type="hidden" name="os0" value="<%= current_user.email %>" maxlength="200">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
            </form>
          </td>
          <td>
            <strong>Credit Card</strong>
            <%= form_tag charges_path(@user) do %>
              <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key= <%= Rails.configuration.stripe[:publishable_key] %>
                data-amount="3600"
                data-email="<%= @user.email %>"
                data-name="Pluspanda Subscription"
                data-description="$36.00 yearly"
                data-image="/images/admin/panda.png">
              </script>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  <% end %>

  <div class="install-page">
    <h3>Install Pluspanda</h3>
    <stong>Place This Code Where You Want Your Testimonials to Display:</stong>
    <p>
      <textarea style="height:200px;"><div id="plusPandaYes"></div><%= embed_code(@user.apikey).html_safe %></textarea>
    </p>
    <h4>TIP: Check out your sample page!</h4>
    <p>
      You can view the page source to see where your code should go. <a href="/users/<%= current_user.id %>/widget/published" target="_blank"> Sample Page</a>
    </p>
  </div>
</div>

app/views/admin/manage.html.haml
:scss
  #manage-pane {
    .panel-1 {
      display: inline-block;
      width: 10%;
      vertical-align: top;
    }
    .panel-2 {
      display: inline-block;
      width: 90%;
      vertical-align: top;
    }
    .table-wrapper-scrollable {
      overflow: auto;
      height: 600px;
      table {
        th {
          text-align: center;
        }
      }
      textarea {
        border: 0;
        border-radius: 0;
        box-shadow: none;
        background-color: transparent;
        padding: 0;
        font-size: 11px;
      }
    }
    .manage-testimonial-filters {
      margin-top: 10px;
    }
    .btn-toolbar {
      margin: 10px 0;
    }
  }
  .workspace {
    position: relative;
  }
.base-padding
  #manage-pane

app/views/admin/published.erb
<div id="plusPandaYes"></div> 

app/views/admin/staged.erb
<style type="text/css">
  <%= @css %>
</style>

<script type="text/javascript">
  <%= @theme_config %>
</script>

<div id="plusPandaYes"></div> 

app/views/admin/staging.erb
<div id="plusPandaYes"></div> 

app/views/admin/testimonials.erb
<% render @testimonials %>

app/views/admin/thanks.html.haml
%h1{ style: "text-align:center; font-size:64px;" }
  Hey Thanks!

%div{ style: "text-align:center"}
  %p{ style:"margin-bottom:10px" }
    I am glad you find pluspanda useful and because of your support I plan to keep developing it further.
  %p{ style:"margin-bottom:10px" }
    You will see your credits in your account section shortly.
    %br
    Soon enough I'll have stuff for you to buy =).
  %p{ style:"margin-bottom:10px" }
    Thanks again!
    %br
    \- Jade

app/views/admin/widget.html.haml
#layout-editor
  .base-padding
    .settings
      = form_for @user.tconfig, :url => "/users/#{ current_user.id }/settings", :html => { :id => "theme-settings-form", :rel => "form.settings", class: "form-horizontal" } do |f|
        %button{type: "submit", style: "display:none" }
        %h3 Settings
        .form-group
          .col-md-4
            %label Testimonials per page
          .col-md-8
            = f.text_field(:per_page, :id => nil, :class => "tconfig_per_page form-control", :maxlength => 3, :style => "width:50px" )
        .form-group
          .col-md-4
            %label Order Testimonials by
          .col-md-8
            = f.select(:sort, Tconfig.sorters, {}, :id => nil, :class => "tconfig_sort form-control" )
            %small{ style: "font-size:0.9em" } Order testimonials in the <strong>Manage Testimonials</strong> section
    .themes
      %h3 Themes
      = form_for Theme.new, :url => "/users/#{ current_user.id }/theme", html: { id: "theme-change-form" } do |f|
        - ThemePackage.themes.each do |name|
          %div{ class: (@theme.theme_name == name) ? "active" : false }= name

    %div{style: "margin-top:30px;"}
      %a.btn.btn-default.btn-lg{ href: "/admin/editor" }
        Launch Theme Editor

    .data-description.buttons{style: "margin-top:30px;"}
      %strong NOTE
      %br
      All changes made only affect the "staging" area. This allows you to freely test changes without affecting your production widget.
      Click "Publish changes" to clone the staging widget into the production widget.
      %p{style: "margin-top:10px;"}
        %a#theme-publish.btn.btn-success.btn-lg{ href: "/users/#{ current_user.id }/theme/publish" } Publish Changes

#layout-previewer
  = render partial: "admin/widget_previewer"