config/routes.rb
Rails.application.routes.draw do
  # legacy api
  resources :testimonials, as: :legacy_testimonials do
    get :widget, :on => :collection, as: :legacy_widget
  end

  # current api
  scope "v1" do
    resources :testimonials do
      # redirect the widget request amazon s3
      # s3 file is the user's themeConfig
      get :widget, :on => :collection, :to => proc {|env|
        apikey = env["QUERY_STRING"].split("=")[1]

        if Rails.env.development?
          user = User.find_by_apikey(apikey)
          # note in development we serve the staged attributes directly
          # even for "published" mode. so we always see staging in published.
          [200, {}, [user.standard_themes.get_staged.generate_theme_config]]
        else
          url = Publish::Config.new(apikey, 'blah').endpoint
          # log    = Rails.root.join('log', 'widget.log')
          # line   = "#{apikey}, #{env["HTTP_REFERER"]}, #{DateTime.now} \n"
          # File.open(log, 'a') { |f| f.write(line) } if File.exist?(log)

          [
            307,
            { 'Location' => url, 'Content-Type' => 'text/html'} ,
            ["redirecting to: #{ url }"]
          ]
        end
      }
    end

  end

  # account management
  resource :account, :controller => "users", :only => [:new, :create] do
    get :reset_password, on: :collection, via: [:get, :post]
  end

  resource :session, :controller => "user_sessions" do
    get "single_access", :on => :member
    get "perishable", :on => :member
  end

  namespace :admin do
    resource :account

    get '/', action: "index"
    get :logout
    get :collect
    get :install
    get :manage
    get :editor
    get :widget
    get :thanks
  end

  resources :users do
    member do
      resources :charges
      put :settings, controller: "api/settings", action: "update"

      scope "/testimonials", controller: "api/testimonials", as: :testimonials do
        get "()", :action => :index
        put "()", :action => :update
        post "/save_positions", :action => :save_positions
      end

      scope "/theme_attributes", :controller => "api/theme_attributes", :as => :theme_attributes, constraints: { attribute: /[\w\-\.]+/ } do
        get "/:attribute/staged" , :action => :staged
        put "/:attribute/staged", :action => :update
        get "/:attribute/original", :action => :original
      end

      scope "/theme", controller: "api/theme", as: :theme do
        post "()", action: :create
        post "/publish", action: :publish
        get "/gallery/:theme", action: :show
        get "/:theme_id/stage", action: :set_staged
      end

      scope "/widget", :controller => 'api/widget', :as => :widget do
        get :staged
        get :published
        get "stock/:theme_name", action: "stock"
      end
    end
  end

  # dashboard
  scope "/pinky", :controller => "pinky", :as => "pinky" do
    get "()" ,:action => "index"
    get "users"
    post "as_user"
  end

  root to: redirect('/admin')
end

app/controllers/pinky_controller.rb
class PinkyController < ApplicationController

  before_filter :authenticate
  
  def index
    
    @logs_top = WidgetLog.order("impressions DESC").limit(50)
    @logs_new = WidgetLog.order("id DESC").limit(50)
    @logs_count = WidgetLog.count  
  end
  
  def users
    @users_count = User.count
    @users_newest = User.limit(50).order("id DESC")
    @users_active = User.limit(50).order("login_count DESC")
    @user_creation_by_month = User.creation_by_month
    @total_by_login_count = User.total_by_login_count
    @stale_users_count = User.stale[0].total
    @unstale_users_count = User.unstale[0].total
  end
  
  def as_user
    user = User.find_by_email(params[:email])
    
    UserSession.create(user)
    
    redirect_to admin_path
  end
  
  private
    
    def authenticate
      pinky = YAML::load(File.open("#{::Rails.root.to_s}/config/pinky.yml"))
      authenticate_or_request_with_http_basic do |user_name, password|
        user_name == pinky["username"] && password == pinky["passkey"]
      end
    end

end

app/views/pinky/index.erb
Total logs: <%= @logs_count %>

<h2>50 Top Widgets</h2>
<table class="data">
  <thead>
    <tr>
      <th>user</th>
      <th>Url</th>
      <th>#</th>
      <th>date</th>
    </tr>
  </thead>
  <tbody>
  <% @logs_top.each do |log| %>
    <tr>
      <td><%= User.find(log.user_id).email %></td>
      <td><%= link_to log.url, log.url, :target => "_blank" %></td>
      <td><%= log.impressions %></td>
       <td><abbr class="timeago" title="<%= Time.parse("#{log.created_at}").iso8601 rescue nil %>"><%= log.created_at %></abbr></td>
    </tr>
  <% end %>
  </tbody>  
</table>

<h2>50 Newest Widgets</h2>
<table class="data">
  <thead>
    <tr>
      <th>user</th>
      <th>Url</th>
      <th>#</th>
      <th>date</th>
    </tr>
  </thead>
  <tbody>
  <% @logs_new.each do |log| %>
    <tr>
      <td><%= User.find(log.user_id).email %></td>
      <td><%= link_to log.url, log.url, :target => "_blank" %></td>
      <td><%= log.impressions %></td>
       <td><abbr class="timeago" title="<%= Time.parse("#{log.created_at}").iso8601 rescue nil %>"><%= log.created_at %></abbr></td>
    </tr>
  <% end %>
  </tbody>  
</table>

app/views/pinky/users.erb
<style type="text/css">
  .column {
    width:49%; 
    display:inline-block;
  }
</style>

<%= form_tag pinky_as_user_path << "?pk=#{params[:pk]}" do %>
  <fieldset>
    <%= text_field_tag :email %>
      <button type="submit">Login as user</button>
  </fieldset>
<% end %>

  <h3>Totals</h3>
  <table class="data">
    <thead>
      <tr>
        <th>Users</th>
        <th>Total</th>
      </tr>  
    </thead>
    <tbody>
      <tr>
        <td>All</td>
        <td><%= @users_count %></td>
      </tr>
      <tr>
        <td>Stale : Older than 30 days w/ &lt;=  3 logins </td>
        <td><%= @stale_users_count %></td>
      </tr>
      <tr>
        <td>UnStale: Older than 30 days w/ &gt;  3 logins</td>
        <td><%= @unstale_users_count %></td>
      </tr>
    </tbody>
  </table>


<br/ style="clear:both">

<div class="column">
  <h3>New Users By Month</h3>
  <table class="data">
    <thead>
      <tr>
        <th>Users</th>
        <th>Month</th>
        <th>Year</th>
      </tr>  
    </thead>
    <tbody>
    <% @user_creation_by_month.each do |entry| %>
      <tr>
        <td><%= entry.total_count%></td>
        <td><%= entry.month %></td>
        <td><%= entry.year %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

<div class="column">

  <h3># Of Users By Login Count</h3>
  <table class="data">
    <thead>
      <tr>
        <th>Logins</th>
        <th>Users</th>
      </tr>  
    </thead>
    <tbody>
    <% @total_by_login_count.each do |entry| %>
      <tr>
        <td><%= entry.logins %></td>
        <td><%= entry.total%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="column">
  <h3>Newest Users</h3>
  <table class="data">
    <thead>
      <tr>
        <th>email</th>
        <th>login count</th>
        <th>last login</th>
      </tr>  
    </thead>
    <tbody>
    <% @users_newest.each do |user| %>
      <tr>
        <td><%= user.email%></td>
        <td><%= user.login_count %></td>
        <td><abbr class="timeago" title="<%= Time.parse("#{user.last_login_at}").iso8601 rescue nil %>"><%= user.last_login_at %></abbr></td>
      </tr>
    <% end %>
    </tbody>
  </table>  

</div>

<div class="column">

  <h3>Most Active Users</h3>
  <table class="data">
    <thead>
      <tr>
        <th>email</th>
        <th>login count</th>
        <th>last login</th>
      </tr>  
    </thead>
    <tbody>
    <% @users_active.each do |user| %>
      <tr>
        <td><%= user.email%></td>
        <td><%= user.login_count %></td>
        <td><abbr class="timeago" title="<%= Time.parse("#{user.last_login_at}").iso8601 rescue nil %>"><%= user.last_login_at %></abbr></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  
</div>