config/routes.rb
Rails.application.routes.draw do
  # legacy api
  resources :testimonials, as: :legacy_testimonials do
    get :widget, :on => :collection, as: :legacy_widget
  end

  # current api
  scope "v1" do
    resources :testimonials do
      # redirect the widget request amazon s3
      # s3 file is the user's themeConfig
      get :widget, :on => :collection, :to => proc {|env|
        apikey = env["QUERY_STRING"].split("=")[1]

        if Rails.env.development?
          user = User.find_by_apikey(apikey)
          # note in development we serve the staged attributes directly
          # even for "published" mode. so we always see staging in published.
          [200, {}, [user.standard_themes.get_staged.generate_theme_config]]
        else
          url = Publish::Config.new(apikey, 'blah').endpoint
          # log    = Rails.root.join('log', 'widget.log')
          # line   = "#{apikey}, #{env["HTTP_REFERER"]}, #{DateTime.now} \n"
          # File.open(log, 'a') { |f| f.write(line) } if File.exist?(log)

          [
            307,
            { 'Location' => url, 'Content-Type' => 'text/html'} ,
            ["redirecting to: #{ url }"]
          ]
        end
      }
    end

  end

  # account management
  resource :account, :controller => "users", :only => [:new, :create] do
    get :reset_password, on: :collection, via: [:get, :post]
  end

  resource :session, :controller => "user_sessions" do
    get "single_access", :on => :member
    get "perishable", :on => :member
  end

  namespace :admin do
    resource :account

    get '/', action: "index"
    get :logout
    get :collect
    get :install
    get :manage
    get :editor
    get :widget
    get :thanks
  end

  resources :users do
    member do
      resources :charges
      put :settings, controller: "api/settings", action: "update"

      scope "/testimonials", controller: "api/testimonials", as: :testimonials do
        get "()", :action => :index
        put "()", :action => :update
        post "/save_positions", :action => :save_positions
      end

      scope "/theme_attributes", :controller => "api/theme_attributes", :as => :theme_attributes, constraints: { attribute: /[\w\-\.]+/ } do
        get "/:attribute/staged" , :action => :staged
        put "/:attribute/staged", :action => :update
        get "/:attribute/original", :action => :original
      end

      scope "/theme", controller: "api/theme", as: :theme do
        post "()", action: :create
        post "/publish", action: :publish
        get "/gallery/:theme", action: :show
        get "/:theme_id/stage", action: :set_staged
      end

      scope "/widget", :controller => 'api/widget', :as => :widget do
        get :staged
        get :published
        get "stock/:theme_name", action: "stock"
      end
    end
  end

  # dashboard
  scope "/pinky", :controller => "pinky", :as => "pinky" do
    get "()" ,:action => "index"
    get "users"
    post "as_user"
  end

  root to: redirect('/admin')
end

app/controllers/api/testimonials_controller.rb
class Api::TestimonialsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound do |exception|
    render(nothing: true, status: :unauthorized)
  end

  before_filter {
    @user = User.find(params[:id])
    authorize! :edit, @user
  }

  def index
    order = "created_at DESC"

    case params[:filter]
    when "published"
      where = {:publish => true, :trash => false}
      order = "position ASC" if @user.tconfig.sort == 'position'
    when "hidden"
      where = {:publish => false, :trash => false}
    when "trash"
      where = {:trash => true}
    else
      where = { :created_at => (Time.now - 2.day)..Time.now, :trash => false }
    end

    limit = 30
    page = params[:page].to_i > 1 ? params[:page].to_i : 1
    offset = ( page*limit ) - limit

    query = @user.testimonials.where(where)
    total = query.count

    testimonials = query
      .order(order)
      .limit(limit)
      .offset(offset)
      .map do |t|
        t.sanitize_for_api
          .merge(t.attributes)
          .merge({
            share_url: view_context.edit_testimonial_url(t.id, apikey: current_user.apikey)
          })
    end

    render json: {
      testimonials: testimonials,
      total: total,
      page: page,
      next_page: (limit*page < total) ? page+1 : false
    }
  end

  def update
    action = params[:do].to_s.downcase
    unless ['publish', 'hide', 'lock', 'unlock', 'trash', 'untrash'].include?(action)
      @message = "Invalid action."
      serve_json_response
      return
    end

    ids = params[:ids].map! { |id| id.to_i }

    case action
    when "publish"
      updates = {:publish => true}
    when "hide"
      updates = {:publish => false}
    when "lock"
      updates = {:lock => true}
    when "unlock"
      updates = {:lock => false}
    when "tag"
      updates = {:tag => params[:tag].to_i}
    when "trash"
      updates = {:trash => true}
    when "untrash"
      updates = {:trash => false}
    end

    count = @user.testimonials.where(id: ids).update_all(updates)

    @status  = "good"
    @message = "#{count} Testimonials update with: #{action}"

    serve_json_response
  end

  def save_positions
    if params['tstml'].nil? or !params['tstml'].is_a?(Array)
      serve_json_response
      return
    end

    t_hash  = {}
    ids = params['tstml'].map! { |id| id.to_i }
    @user.testimonials.find(ids).map { |t| t_hash[t.id.to_s] = t }
    ids.each_with_index do |id, position|
      t = t_hash[id.to_s]
      t.position = position
      t.save
    end

    @status  = "good"
    @message = "Positions Saved!"

    serve_json_response
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

  layout "testimonials"

  # TODO this is for testing only
  skip_before_filter :verify_authenticity_token
  before_filter :allow_iframe_requests

  def index
    @user = User.find_by_apikey!(params['apikey'])

    @active_tag   = (params['tag'].nil?)  ? 'all'    : params['tag']
    @active_sort  = (params['sort'].nil?) ? 'newest' : params['sort'].downcase
    @active_page  = (params['page'].nil? ) ? 1       : params['page'].to_i
    @tags  = Tag.where({:user_id => @user.id })

    criteria = {
      user_id: @user.id,
      premium: @user.premium,
      limit: @user.tconfig.per_page,
      sort: @user.tconfig.sort,
      page: @active_page,
      tag: @active_tag,
      created: @active_sort
    }

    @testimonials = Testimonial.from_user(criteria).map { |t| t.sanitize_for_api }
    update_data = Testimonial.update_data_payload(criteria.merge({
                    apikey: @user.apikey,
                    average: @user.testimonials.average(:rating).to_f
                  }))

    respond_to do |format|
      format.any(:html, :iframe) { render :text => 'a standalone version maybe?'}
      format.json do
        render json: {
          update_data: update_data,
          testimonials: @testimonials
        }
      end
      format.js do
        #@response.headers["Cache-Control"] = 'no-cache, must-revalidate'
        #@response.headers["Expires"] = 'Mon, 26 Jul 1997 05:00:00 GMT'
        render :js => "panda.display(#{@testimonials.to_json});panda.update(#{update_data.to_json});"
      end
    end
  end

  def new
    @user = User.find_by_apikey!(params['apikey'])
    @testimonial = Testimonial.new({
      :name  => params[:name],
      :email => params[:email],
      :meta  => params[:meta]
    })

    respond_to do |format|
      format.any(:html, :iframe) do
        render "editor", formats: [:html]
      end
    end
  end

  def create
    @user = User.find_by_apikey!(params['apikey'])

    params[:testimonial] ||= {}
    params[:testimonial].delete('publish')
    params[:testimonial].delete('lock')

    unless can_publish_new
      @testimonial = Testimonial.new(testimonial_params)
      render "editor", formats: [:html]
      return
    end

    @testimonial = @user.testimonials.new(testimonial_params)

    if @testimonial.save
      UserMailer.new_testimonial(@user, @testimonial).deliver if @user[:is_via_api]
      @testimonial.freeze
      @status   = "good"
      @message  = "Testimonial created!"
      @resource = @testimonial

      if params["is_ajax"]
        serve_json_response
      else
        respond_to do |format|
          format.any(:html, :iframe) do
            flash[:success] = @message
            redirect_to "#{ edit_testimonial_path(@testimonial, apikey: @user.apikey) }"
          end
          format.json { serve_json_response }
        end
      end
    else
      if @testimonial.valid?
        @message = "Oops! An unknown error occured. Please try again."
        respond_to do |format|
          format.any(:html, :iframe) { flash[:notice] = @message }
          format.json { serve_json_response }
        end
      else
        @message  = "Please make sure all fields are valid!"
        respond_to do |format|
          format.any(:html, :iframe) {
            flash[:notice] = @message
            @testimonial = Testimonial.new(testimonial_params)
            render "editor", formats: [:html]
          }
          format.json { serve_json_response }
        end
      end
    end
  rescue ActionController::ParameterMissing
    message = "Missing required fields."
    render json: {status: "bad", message: message}, status: 401
  end

  def edit
    @user = User.find_by_apikey!(params['apikey'])
    @testimonial = @user.testimonials.find(params[:id])

    respond_to do |format|
      format.any(:html, :iframe) do
        render "editor", formats: [:html]
      end
    end
  end

  WritableAttributes = [
    :name,
    :location,
    :c_position,
    :position,
    :company,
    :rating,
    :url,
    :body,
    :publish,
    :lock,
    :email,
    :trash,
    :avatar
  ]

  def update
    @user = User.find_by_apikey!(params['apikey'])
    @testimonial = @user.testimonials.find(params[:id])

    params[:testimonial] ||= {}
    params[:testimonial].delete('publish')
    params[:testimonial].delete('lock')
    params.merge!(params[:testimonial])
    params.delete(:testimonial)

    if cannot?(:edit, @testimonial)
      # Throw exception
      @message = "This testimonial is locked!"

      respond_to do |format|
        format.any(:html, :iframe) do
          flash[:notice] = @message
          redirect_to "#{ edit_testimonial_path(@testimonial, apikey: @user.apikey) }"
        end
        format.json { render json: { message: @message }, status: 423 }
      end

      return
    end

    # temp hack to ensure core attributes are saved even if image fails
    if params && params[:avatar]
      core_attrs = params.dup
      core_attrs.delete(:avatar)
      attributes = WritableAttributes.dup - [:avatar]
      @testimonial.update_attributes(core_attrs.permit(*attributes))
    end

    if @testimonial.update_attributes(params.permit(*WritableAttributes))
      @status   = "good"
      @message  = "Testimonial Updated!"
      @resource = @testimonial

      if params["is_ajax"]
        serve_json_response
      else
        respond_to do |format|
          format.any(:html,:iframe) do
            flash[:success] = @message
            redirect_to "#{ edit_testimonial_path(@testimonial, apikey: @user.apikey) }"
          end
          format.json { serve_json_response }
        end
      end
    else
      if @testimonial.valid?
        respond_to do |format|
          format.any(:html, :iframe) {
            flash[:notice] = @testimonial.errors.to_a.join(', ')
            redirect_to "#{ edit_testimonial_path(@testimonial, apikey: @user.apikey) }"
          }
          format.json { serve_json_response }
        end
      else
        @message = "Oops! Please make sure all fields are valid!"
        respond_to do |format|
          format.any(:html, :iframe) { flash[:notice] = @message }
          format.json { serve_json_response }
        end
      end
    end
  end

  private

  # verify this user can create a testimonial
  def can_publish_new
    return true if @user == current_user
    access_key = @user.tconfig.form["require_key"]

    email = (testimonial_params[:email].nil?) ? '' : testimonial_params[:email].strip

    if access_key.present? && access_key != params[:access_key]
      flash[:notice] = "Invalid Access Key!"
    elsif testimonial_params[:name].nil? || testimonial_params[:name].strip.blank?
      flash[:notice] = "Please enter your full name."
    elsif @user.tconfig.form["email"] && (email.blank? || email.index('@') == nil)
      flash[:notice] = "Please enter a valid email address."
    else
      return true
    end

    false
  end

  def testimonial_params
    params.require(:testimonial).permit(*WritableAttributes)
  end

  def allow_iframe_requests
    response.headers.delete("X-Frame-Options")
  end
end

app/views/testimonials/_editor.form.erb
<%
image_source  = @testimonial.avatar_file_name.nil? || @testimonial.avatar_file_name.empty? ? "/images/stock.png" : @testimonial.avatar.url(:sm) 
%>

<% if !current_user && @testimonial.lock %>
  <div class="notice"><h1>This Testimonial is locked!</h1></div>
<% end %>

<% if flash[:notice] %>
  <div class="notice"><h1><%= flash[:notice] %></h1></div>
<% end %>
    
<div id="editor-wrapper">

<% form_for @testimonial, :html => { :multipart => true, :class => "js-multipart-form" } do |f| %>
  <%= hidden_field_tag(:apikey, params[:apikey]) if params['apikey'] %>
  
<% if !current_user %>
  <div class="panda-image">
    Testimonial
  </div>
<% end %>   
  <div class="t-view">
    <div id="t-view-inner">
      
      <div class="t-content">    
        <div class="rating-fallback">
          Select a rating  <%= f.select(:rating, [['5 stars',5],['4 stars',4],['3 stars',3],['2 stars',2],['1 star',1]])%>
        </div>

        <div class="t-body">
          <%= f.text_area :body %>
        </div>
         
        <fieldset>
          <label>Full Name</label>
          <%= f.text_field :name %>
        </fieldset>
        
        <fieldset>
          <label>Company</label>
          <%= f.text_field :company %>
         </fieldset>

        <fieldset>
          <label>Role at Company</label>
          <%= f.text_field :c_position %>
        </fieldset>
                
        <fieldset>       
          <label>Location</label>
          <%= f.text_field :location %>
        </fieldset>
        
        <fieldset>        
          <label>Website</label>
          <%= f.text_field :url %>
        </fieldset> 
               
      </div>

      <div class="t-details">
        Upload new headshot or logo
        <%= f.file_field :avatar, :style => "width:180px" %>
        <div id="testimonial-image-wrapper" class="image" rel="<%= @testimonial.avatar.url(:sm) %>">
           <%= image_tag image_source %>
        </div>
        
        <fieldset>
          <label>Select Category</label>
          (tag list)
        </fieldset>

        <fieldset>
          <%= @testimonial.created_at %>
        </fieldset>
                
        <% if current_user %>
          <div id="admin-extra">
            Lock Testimonial? 
            <%= f.check_box :lock %>
            <%= f.label(:lock, "(yes)", :style => "display:inline;") %>          
            <div class="t-publish">
              Publish? 
              <%= f.check_box :publish %>
              <%= f.label(:publish, "(yes)", :style => "display:inline;") %>              
            </div>
          </div>
        <% end %>
        
        <div class="round-box-tabs buttons">
          <button class="submit-button positive" type="submit">Save Changes</button>
        </div>
      </div>
            
    </div>
  </div>

<% end %>
</div>

app/views/testimonials/_form.erb
<%
rand   = 'random'
image = ''
#image  = (empty($testimonial->image))
#  ? ''
#  : "<img src=\"$image_url/$testimonial->image?r=rand\"/>";
%>
<div class="admin-testimonial-wrapper t-builder-wrapper">

<!-- old if = save-testimonial rel has the testimonial id -->
<% form_for @testimonial do |f| %>

  <div class="panda-image">
    <a href="#close" class="close">[X]</a>
    Upload new headshot or logo <input type="file" name="image" />
  </div>  
  <div class="t-view">
    <div style="margin:auto;width:725px;">
      <div class="t-details">
        <a href="/admin/testimonials/manage/crop?image=<?php echo $testimonial->image?>" rel="facebox">Edit Image</a>
        
        <div class="image" rel="<?php echo $image_url?>">
          <?php echo $image?>
        </div>
        
        <span class="label">Full Name</span>
        <span class="t-name">
          <%= f.text_field :name %>
        </span>
        
        <span class="label">Position at Company</span>
        <span class="t-position">
          <%= f.text_field :c_position %>
        </span>
        
        <span class="label">Company</span>
        <span class="t-company">
          <%= f.text_field :company %>
        </span>
        
        <span class="label">Location</span>
        <span class="t-location">
          <%= f.text_field :location %>
        </span>
        
        <span class="label">Website</span>
        <span class="t-url">
        http://<%= f.text_field :url %>
        </span>
      </div>
      
      <div class="t-content">
        
        <span style="display:none">
          <%= f.hidden_field :rating %>
          <!--
          <?php echo common_build::rating_select_nice($testimonial->rating)?>
          -->
        </span>        
        <div class="rating-fallback">
          Select a rating 
          <!--
          <?php echo common_build::rating_select_dropdown($testimonial->rating);?>
          -->
        </div>

        <div class="t-body">
          <%= f.text_area :body %>
        </div>
        
        <div class="t-date">
          <%= @testimonial.created_at %>
          <!--<?php echo common_build::timeago($testimonial->created)?>-->
        </div>
      
        <div class="t-tag">
          (tag list)
        </div>
        
        <div class="admin-extra">
          Lock Testimonial? 
          <%= f.check_box :lock %>
          <%= f.label(:lock, "(yes)") %>          
          <div class="t-publish">
            Publish? 
            <%= f.check_box :publish %>
            <%= f.label(:publish, "(yes)") %>              
          </div>
        </div>
      </div>

      <div class="round-box-tabs buttons" style="clear:both">
        <button class="submit-button positive" type="submit">Save Changes</button>
      </div>
    
    </div>
  </div>

<% end %>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $(document).trigger('tstml.edit');
  });
</script>

app/views/testimonials/_new.gatekeeper.erb
<div class="message-wrapper">
  <%=raw @user.tconfig.message %>
</div>

<% if flash[:notice] %>
  <div class="notice"><h1><%= flash[:notice] %></h1></div>
<% end %>

<div id="public-top">Thank You For Your Time!</div>
<%= form_for @testimonial do |f| %>
  <%= hidden_field_tag(:apikey, params[:apikey]) if params['apikey'] %>
  
<% if !@user.tconfig.form["require_key"].empty? %>
  <fieldset>
    <label>Access Key <span class="req_star">*</span></label>
    <%= text_field_tag :access_key, params[:access_key], :rel => "text_req" %>
  </fieldset>
<% end %>

  <fieldset class="panda-name "> 
	  <label>Full Name <span class="jade_required_star">*</span></label> 
	  <%= f.text_field :name, :rel => "text_req" %>
  </fieldset>
  
<% if @user.tconfig.form["email"] %> 
  <fieldset class="panda-email "> 
	  <label>Email <span class="req_star">*</span></label> 
	  <%= f.text_field :email, :rel => "email_req" %>
  </fieldset>	
<% end %>

<% if !@user.tconfig.form["meta"].empty? %>
  <fieldset class="panda-meta "> 
	  <label>Order #</label>
	  <%= f.text_field :meta, :rel => "text_req" %>
  </fieldset>
<% end %>		
		
  <fieldset class="buttons">
    <button type="submit" class="positive">Build Your Testimonial!</button>
  </fieldset>
<% end %>

app/views/testimonials/_tag_list.erb
<% extra ||= false %>
  
<ul class="pandA-tTags_ness">
  <li><a href="#all" class="active">Everyone</a></li>
<% if extra %>
  <% extra.each do |val, text| %>
      <li><a href="#<%= val %>"><%= text %></a></li>
  <% end %>
<% end %>

<% for tag in tags do %>
  <li><a href="#<%= tag.id %>"><%= tag.name %></a></li>
<% end %>
</ul>

app/views/testimonials/_theme_config.js.erb
(function() {
    window.pandaSettings = <%= MultiJson.encode(pandaSettings).html_safe %>;
    window.pandaThemeConfig = {
        cssUrl : '<%= stylesheet %>',
        wrapperHTML : '<%= raw wrapper_html %>',
        testimonialHTML : function(item) {
            return '<%= raw testimonial_html %>';
        }
    }

    var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
    s.src = '<%= widget_url %>';
    document.body.appendChild(s);
})();

app/views/testimonials/editor.html.haml
- form_options = @user.tconfig.form
%style
  :plain
    .form-horizontal label {
      text-align:right;
    }
    .alert {
      margin:0;
      padding:10px;
    }

.message-wrapper{ style:"padding:10px;" }
  = raw @user.tconfig.message

= form_for @testimonial, :html => { :multipart => true, :class => "js-multipart-form form-horizontal" } do |f|

  - if params['apikey']
    = hidden_field_tag(:apikey, params[:apikey])
  #status.form-group
    .col-xs-8.col-xs-offset-4
      - if @testimonial.lock
        .alert.alert-danger
          This Testimonial is locked!
      - elsif flash[:success]
        .alert.alert-success
          = flash[:success]
      - elsif flash[:notice]
        .alert.alert-danger
          = flash[:notice]

  - if form_options["require_key"].present?
    .form-group
      %label.col-xs-4
        Access Key
        %span.req_star *
      .col-xs-8
        = text_field_tag :access_key, params[:access_key], :rel => "text_req", class: "form-control"
  .form-group
    %label.col-xs-4
      Full Name
      %span.req_star *
    .col-xs-8
      = f.text_field :name, :rel => "text_req", class: "form-control"
  - if form_options["email"]
    .form-group
      %label.col-xs-4
        Email
        %span.req_star *
      .col-xs-8
        = f.text_field :email, :rel => "email_req", class: "form-control"
  - if form_options["meta"].present?
    .form-group
      %label.col-xs-4
        = form_options["meta"]
        %span.req_star *
      .col-xs-8
        = f.text_field :meta, :rel => "text_req", class: "form-control"

  .form-group
    %label.col-xs-4 Testimonial
    .col-xs-8
      = f.text_area :body, class: "form-control", style: "height:100px;"

  - unless [false, 'off'].include? form_options["rating"]
    .form-group
      %label.col-xs-4 Select a rating
      .col-xs-8.rating-fallback
        = f.select(:rating, [['5 stars',5],['4 stars',4],['3 stars',3],['2 stars',2],['1 star',1]])

  - unless [false, 'off'].include? form_options["company"]
    .form-group
      %label.col-xs-4 Company
      .col-xs-8
        = f.text_field :company, class: "form-control"

  - unless [false, 'off'].include? form_options["location"]
    .form-group
      %label.col-xs-4 Location
      .col-xs-8
        = f.text_field :location, class: "form-control"

  - unless [false, 'off'].include? form_options["c_position"]
    .form-group
      %label.col-xs-4 Role at Company
      .col-xs-8
        = f.text_field :c_position, class: "form-control"

  - unless [false, 'off'].include? form_options["website"]
    .form-group
      %label.col-xs-4 Website
      .col-xs-8
        = f.text_field :url, class: "form-control"

  - unless [false, 'off'].include? form_options["avatar"]
    .form-group
      %label.col-xs-4 Headshot or Logo
      .col-xs-8
        = f.file_field :avatar, style: "width:180px"
        #testimonial-image-wrapper.image{rel: @testimonial.avatar.url(:sm)}
          = image_tag @testimonial.image_source
  .form-group
    .col-xs-8.col-xs-offset-4
      %strong.pull-right{ style: "line-height:32px;"}
        Powered by
        %a{ href: "http://pluspanda.com" } http://pluspanda.com

      %button.submit-button.btn.btn-success{type: "submit"} Save Changes

app/views/testimonials/tag_list.erb
<% extra ||= false %>

  <ul>
    <li><a href="#all" class="active">Everyone</a></li>
  <% if extra %>
    <% extra.each do |val, text| %>
        <li><a href="#<%= val %>"><%= text %></a></li>
    <% end %>
  <% end %>
  
  <% for tag in tags do %>
    <li><a href="#<%= tag.id %>"><%= tag.name %></a></li>
  <% end %>
  </ul>

app/views/testimonials/widget_settings.erb
/*<%= Time.new %>*/
var pandaSettings = {
  apiUrl : '<%= root_url %>',
  apiVrsn : '<%= api_version_number %>',
  apikey : '<%= user.apikey %>',
  theme : '<%= user.tconfig.theme %>',
  cssUrl : '<%= "#{root_url}/system/data/#{user.apikey}/#{user.tconfig.theme}.css" %>',
  structure : '<%= raw panda_structure %>',
  itemHtml : function(item){
    return '<%= raw item_html %>';
  }
}

app/views/testimonials/widget_settings.js.erb
/*<%= Time.new %>*/
var pandaSettings = {
  apiUrl : '<%= root_url %>',
  apiVrsn : '<%= api_version_number %>',
  apikey : '<%= user.apikey %>'
}

var pandaThemeConfig = {
  cssUrl : '<%= "#{root_url}/system/data/#{user.apikey}/publish.css" %>',
  wrapperHTML : '<%= raw wrapper_html %>',
  testimonialHTML : function(item){
    return '<%= raw testimonial_html %>';
  }
}